n = input('Digite alguma coisa')
print('O tipo primitivo desse valor é', type(n))
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Tem casas decimais?', n.isdecimal())
print('Está em minúscula?', n.islower())
print('Está em máiscula?', n.isupper())
print('Só tem espaços?', n.isspace())
print('Está capitalizada?', n.istitle())

n = input('Digite alguma coisa')
print(f'O tipo primitivo desse valor é {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'É um número? {n.isnumeric()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É alfanumérico? {n.isalnum()}')
print(f'Está em maiúsculas? {n.isupper()}')
print(f'Está em minúsculas? {n.islower()}')
print(f'Está capitalizado? {n.istitle()}')
